
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\User\Communication\Controller\:
        resource: '../src/User/Communication/Controller'
        tags: ['controller.service_arguments']

    App\User\Persistence\Entity\:
        resource: '../src/User/Persistence/Entity'
        tags: ['doctrine.repository_service']

    App\GameCore\Persistence\Entity\:
        resource: '../src/GameCore/Persistence/Entity'
        tags: ['doctrine.repository_service']

