
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\User\Communication\Controller\:
        resource: '../src/User/Communication/Controller'
        tags: ['controller.service_arguments']

    App\GameBetting\Communication\Controller\:
        resource: '../src/GameBetting/Communication/Controller'
        tags: ['controller.service_arguments']

    App\GameExtraBetting\Communication\Controller\:
        resource: '../src/GameExtraBetting/Communication/Controller'
        tags: ['controller.service_arguments']

    App\GameRating\Communication\Controller\:
        resource: '../src/GameRating/Communication/Controller'
        tags: ['controller.service_arguments']

    App\User\Persistence\Entity\:
        resource: '../src/User/Persistence/Entity'
        tags: ['doctrine.repository_service']

    App\GameCore\Persistence\Entity\:
        resource: '../src/GameCore/Persistence/Entity'
        tags: ['doctrine.repository_service']

    App\GameExtraBetting\Persistence\Entity\:
        resource: '../src/GameExtraBetting/Persistence/Entity'
        tags: ['doctrine.repository_service']

    App\GameApi\Communication\Command\:
        resource: '../src/GameApi/Communication/Command'
        tags: ['console.command']

    App\GameRating\Business\GamePoints\Points:
        arguments:
            - '@App\GameRating\Business\GamePoints\Collection\NoWin'
            - '@App\GameRating\Business\GamePoints\Collection\WinExact'
            - '@App\GameRating\Business\GamePoints\Collection\WinScoreRightDiff'
            - '@App\GameRating\Business\GamePoints\Collection\WinTeam'

